-- 角色表增加业务数据范围类型和绑定分销商
ALTER TABLE `sys_role` ADD COLUMN `data_scope_type` VARCHAR(30) DEFAULT NULL COMMENT '业务数据范围: ALL/DISTRIBUTOR_SELF/DISTRIBUTOR_CUSTOM/MERCHANT_SELF/MERCHANT_CUSTOM';
ALTER TABLE `sys_role` ADD COLUMN `distributor_id` BIGINT DEFAULT NULL COMMENT '绑定分销商ID(分销商/商家角色)';
